### ISSUE TITLE
Update Package files and metadata with Bagger with Quick Start Guide instructions for BagIt-Python

### ISSUE THREAD

**Issue by kemartin2015** [BitCurator/documentation#12]
Bagger is no longer supported.

Update [Package files and metadata with Bagger](https://github.com/BitCurator/documentation/blob/main/docs/All%20Step-by-Step%20Guides/Packaging%20and%20Transfer%20Guides/Package%20files%20and%20metadata%20with%20Bagger.md#package-files-and-metadata-with-bagger) with [BagIt-Python instructions ](https://github.com/BitCurator/bitcurator-distro/wiki/BitCurator-Quick-Start-Guide#creating-bagit-packages-for-secure-transfer-with-bagit-python)from Quick Start Guide.

**Comment by bedwards254** [comment]
Branched and ready for review!

**Comment by decirella** [comment]
Thanks @bedwards254 this looks great! I made an addition to the section index page to link to the new page: https://github.com/BitCurator/documentation/commit/7a29bf85d873d7cb962fddb370c2e013fe9d801e

Will pull, merge, and re-deploy now
