### ISSUE TITLE
Invalid Bulk Extractor wiki link

### ISSUE THREAD

**Issue by kemartin2015** [BitCurator/documentation#13]
Invalid link for [Bulk Extractor Viewer](https://github.com/BitCurator/documentation/blob/69699b80d565e39a2c11e5e4f17733e1436a50af/docs/All%20Step-by-Step%20Guides/Forensics%20and%20Reporting%20Guides/Bulk%20Extractor%20Viewer.md?plain=1#L10) 

`The Bulk Extractor Viewer (BEviewer) is a graphical interface for [bulk\_extractor](https://forensicswiki.xyz/wiki/index.php?title=Bulk_extractor), "a C++ program that scans a disk image, a file, or a directory of files and extracts useful information without parsing the file system or file system structures. The results can be easily inspected, parsed, or processed with automated tools. bulk\_extractor also creates a histogram of features that it finds, as features that are more common tend to be more important."`

Correct link: https://forensics.wiki/bulk_extractor/

**Comment by decirella** [comment]
Correct link added in: https://github.com/BitCurator/documentation/commit/298816aca29aa4fbbd20b454a58fbf14aa2ce55a
