### ISSUE TITLE
Add Bulk Reviewer instructions from Quick Start Guide

### ISSUE THREAD

**Issue by kemartin2015** [BitCurator/documentation#14]
The legacy wiki had no instructions for Bulk Reviewer. Add instructions from Quick Start Guide under Forensics and Reporting: [Scanning Disk Images and Directories with Bulk Reviewer](https://github.com/BitCurator/bitcurator-distro/wiki/BitCurator-Quick-Start-Guide#scanning-disk-images-and-directories-with-bulk-reviewer)

**Comment by bedwards254** [comment]
I'm happy to be assigned this one - I just can't seem to do it myself and don't want to fork/branch before then just in case!

**Comment by bedwards254** [comment]
Branched and ready for review!
