### ISSUE TITLE
Add Brunnhilde instructions from Quick Start Guide 

### ISSUE THREAD

**Issue by kemartin2015** [BitCurator/documentation#15]
The legacy wiki has no instructions for Brunnhilde. Add instructions from Quick Start Guide under Forensics and Reporting: [Analyzing a Disk Image with Brunnhilde](https://github.com/BitCurator/bitcurator-distro/wiki/BitCurator-Quick-Start-Guide#analyzing-a-disk-image-with-brunnhilde).

**Comment by bedwards254** [comment]
I'm happy to be assigned this one - I just can't seem to do it myself and don't want to fork/branch before then just in case!

**Comment by decirella** [comment]
Thanks @bedwards254 please feel free to fork/branch and submit a pull request with any contributions.

**Comment by bedwards254** [comment]
Branched and ready for review!

**Comment by decirella** [comment]
Looks great, thanks for your contributions!
