### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by a-berish** [BitCurator/documentation#3]
https://github.com/bitcurator/bitcurator-distro-salt is invalid, find replacement link.

https://github.com/BitCurator/documentation/blob/69699b80d565e39a2c11e5e4f17733e1436a50af/docs/Installing%20BitCurator/Installing%20BitCurator.md?plain=1#L35

**Comment by decirella** [comment]
Thanks! Link updated in: https://github.com/BitCurator/documentation/commit/39f7a32d5ec28bac52406c487e2a82d620527de7
