### ISSUE TITLE
Update Getting Started page with edit-a-thon suggestions

### ISSUE THREAD

**Issue by a-berish** [BitCurator/documentation#5]
Update [Installing BitCurator wiki page](https://github.com/BitCurator/documentation/blob/main/docs/Installing%20BitCurator/Installing%20BitCurator.md) with [changes from edit-a-thon](https://docs.google.com/document/d/1cyBP85IjUTtBkfOfUuUDD_nVl12UFpv48SEXJOhEn6E/edit?usp=sharing)

**Comment by decirella** [comment]
These changes have been completed, ready for review
