### ISSUE TITLE
Update Installation via Live ISO with Quick Start Guide instructions

### ISSUE THREAD

**Issue by a-berish** [BitCurator/documentation#6]
Edit or replace [Installation via Live ISO](https://github.com/BitCurator/documentation/blob/main/docs/Installing%20BitCurator/Installation%20via%20Live%20ISO.md) with [Install Option1: Deploy on a Clean Ubuntu Host or VM](https://github.com/BitCurator/bitcurator-distro/wiki/BitCurator-Quick-Start-Guide#install-option-1-deploy-on-a-clean-ubuntu-host-or-vm) from Quick Start Guide.

**Comment by bedwards254** [comment]
Branched and ready for review!
