### ISSUE TITLE
Update the tools listed within the Imaging and Recovery Guides landing page

### ISSUE THREAD

**Issue by a-berish** [BitCurator/documentation#8]
Update/add the following text from [Working in the BitCurator Environment, QS Guide](https://github.com/BitCurator/bitcurator-distro/wiki/BitCurator-Quick-Start-Guide#working-in-the-bitcurator-environment)

"The Imaging and Recovery submenu lists tools to assist in device imaging and recovery. These include:
- Brasero: A GNOME application to burn CDs and DVDs, and create 1:1 copies of CDs and DVDs.
- cdrdao: An application to record audio or data CD-Rs in disk-at-once (DAO) mode based on a textual description of the CD contents ([toc-file](http://cdrdao.sourceforge.net/example.html#toc-file-example)).
- Clonezilla: A partition and disk imaging/cloning program.
- dcfldd: An enhanced version of GNU dd with features useful for forensics and security, including hashing on-the-fly and split outputs.
- dd: dd copies input to output with a changeable I/O block size, while optionally performing conversions on the data. Can be used to create raw images of devices.
- ddrescue: A data recovery tool with advanced features to assist in rescue of good data from devices with read errors.
- dumpfloppy: A tool to read floppy disks in arbitrary formats supported by the PC floppy controller, and work with the resulting image files.
- ewfacquire: A utility to acquire media data from a source and store it in EWF format (Expert Witness Compression Format).
- Guymager: A GUI tool to create raw and EWF-packaged images from devices."

to [Imaging and Recovery Guides](https://github.com/BitCurator/documentation/blob/main/docs/All%20Step-by-Step%20Guides/Imaging%20and%20Recovery%20Guides.md)

**Comment by decirella** [comment]
Thanks @bparnin !
